language: node_js
node_js:
  - node
  - io.js
  - 0.12
  - 0.10

pre_script: 'sudo npm install -g eslint'

after_script: "npm run test-cov && cat ./coverage/lcov.info | codecov && cat ./coverage/lcov.info | coveralls"
